apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi
  labels:
    app: testapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapi
  template:
    metadata:
      labels:
        app: testapi
    spec:
      containers:
      - name: testapi
        image: testapik8s:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

---

apiVersion: v1
kind: Service
metadata:
  name: testapi-service
spec:
 type: LoadBalancer
 ports:
 - port: 80
 selector:
   app: testapi


